version: '2.2'

services:
  uam_1:
    image: debian:bullseye-slim
    container_name: uam_1
    restart: always
    cap_add:
      - NET_ADMIN
    ulimits:
      memlock: -1
    volumes:
      - "./entrypoint_test.sh:/opt/entrypoint.sh"
    command: /bin/sh -c "chmod +x /opt/entrypoint.sh && /opt/entrypoint.sh $${PBKEY}"
    environment:
      - PBKEY=${PBKEY}
