version: '3.3'

services:
  uam_1:
    image: debian:bullseye-slim
    container_name: uam_1
    restart: always
    cap_add:
      - IPC_LOCK
    volumes:
      - "./entrypoint.sh:/opt/entrypoint.sh"
    command: /bin/sh -c "chmod +x /opt/entrypoint.sh && /opt/entrypoint.sh $${PBKEY}"
    environment:
      - PBKEY=${PBKEY}

  uam_2:
    image: debian:bullseye-slim
    container_name: uam_2
    restart: always
    cap_add:
      - IPC_LOCK
    volumes:
      - "./entrypoint.sh:/opt/entrypoint.sh"
    command: /bin/sh -c "chmod +x /opt/entrypoint.sh && /opt/entrypoint.sh $${PBKEY}"
    environment:
      - PBKEY=${PBKEY}
